server:
  port: 8084

spring:
  kafka:
    producer:
      key-serializer: com.nylgsc.config.ObjectSerializer
      value-serializer: com.nylgsc.config.ObjectSerializer
    consumer:
      key-deserializer: com.nylgsc.config.ObjectDeSerializer
      value-deserializer: com.nylgsc.config.ObjectDeSerializer
      group-id: 0
      auto-offset-reset: earliest
      enable-auto-commit: true
    bootstrap-servers: 192.168.253.129:9092
  redis:
    host: 192.168.253.129
    port: 6381
    password: 123456
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/redismysql?&autoReconnect=true&failOverReadOnly=false&useSSL=false&characterEncoding=UTF-8

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



redisson:
  address: redis://192.168.253.129:6381
  password: 123456


